%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% transient %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Final iteration number
Niter2 = 50;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% transient edit part
freq = 1e9;
cycle = 3;
T = 1/freq;
Vamp = 1e-3;
Nstep = 100;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% excitation voltage
Vex = 500e-3;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
totalNstep = Nstep*cycle;
totalT = T*cycle;
deltaT = T/Nstep;
time = 0:deltaT:totalT;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
save_phi_update = zeros(Niter2,1);
save_update = zeros(size(X2_sorted,1),1);

In = zeros(totalNstep+1,1);
Ip = zeros(totalNstep+1,1);
Id = zeros(totalNstep+1,1);

for step=1:totalNstep+1

    old_phi = phi(:,1);
    old_n = n(:,1);
    old_p = p(:,1);

    for it=1:Niter2

        Jaco = sparse(size(X2_sorted,1),size(X2_sorted,1));
        Res = zeros(size(X2_sorted,1),1);

        saveexl = zeros(size(X1,1),1);

        for i=1:Esirow
            if i <= E2row
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,1),2)) = saveexl(X1_sorted(Esi(i,1),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2));
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2))*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,2),2)) = saveexl(X1_sorted(Esi(i,2),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1)...
                    + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,3),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,1),2));
                saveexl(X1_sorted(Esi(i,3),2)) = saveexl(X1_sorted(Esi(i,3),2)) + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4;

            elseif i > E2row && i <= (E2row + E3row)
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,1),2)) = saveexl(X1_sorted(Esi(i,1),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2));
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2))*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,2),2)) = saveexl(X1_sorted(Esi(i,2),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1)...
                    + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,3),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,1),2));
                saveexl(X1_sorted(Esi(i,3),2)) = saveexl(X1_sorted(Esi(i,3),2)) + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4;

            elseif i > (E2row+E3row) && i <= Esirow
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,1),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,1),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,1),2)) = saveexl(X1_sorted(Esi(i,1),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,3)*lenEsi(i,3))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2));
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1);
                Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,2),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,2),2))-2,1),1)...
                    + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,1)/lenEsi(i,1) + edgeEsi(i,2)/lenEsi(i,2))*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,1)/lenEsi(i,1)*phi(X1_sorted(Esi(i,1),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,3),2));
                saveexl(X1_sorted(Esi(i,2),2)) = saveexl(X1_sorted(Esi(i,2),2)) + (edgeEsi(i,1)*lenEsi(i,1) + edgeEsi(i,2)*lenEsi(i,2))/4;

                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,3),2))-2,1))...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3));
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,2),2))-2,1))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2);
                Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1)) = Jaco(X2(3*(X1_sorted(Esi(i,3),2))-2,1), X2(3*(X1_sorted(Esi(i,1),2))-2,1))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3);
                Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1) =  Res(X2(3*(X1_sorted(Esi(i,3),2))-2,1),1)...
                    + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4*q/e0*Nd...
                    - esi*(edgeEsi(i,2)/lenEsi(i,2) + edgeEsi(i,3)/lenEsi(i,3))*phi(X1_sorted(Esi(i,3),2))...
                    + esi*edgeEsi(i,2)/lenEsi(i,2)*phi(X1_sorted(Esi(i,2),2))...
                    + esi*edgeEsi(i,3)/lenEsi(i,3)*phi(X1_sorted(Esi(i,1),2));
                saveexl(X1_sorted(Esi(i,3),2)) = saveexl(X1_sorted(Esi(i,3),2)) + (edgeEsi(i,2)*lenEsi(i,2) + edgeEsi(i,3)*lenEsi(i,3))/4;
            end
        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%%  for electron
        for i=1:V_silicon_row
            %%% - qn
            Jaco(X2(3*V_silicon(i,2)-2),X2(3*V_silicon(i,2)-1)) = Jaco(X2(3*V_silicon(i,2)-2),X2(3*V_silicon(i,2)-1)) - saveexl(V_silicon(i,2))*q/e0;
            Res(X2(3*V_silicon(i,2)-2),1) = Res(X2(3*V_silicon(i,2)-2),1) - saveexl(V_silicon(i,2))*q/e0*n(i);
            %%% + qp
            Jaco(X2(3*V_silicon(i,2)-2),X2(3*V_silicon(i,2))) =  Jaco(X2(3*V_silicon(i,2)-2),X2(3*V_silicon(i,2))) + saveexl(V_silicon(i,2))*q/e0;
            Res(X2(3*V_silicon(i,2)-2),1) = Res(X2(3*V_silicon(i,2)-2),1) + saveexl(V_silicon(i,2))*q/e0*p(i);
        end

        %%%  for electron DD
        for i=1:Esirow

            f1 = find(V_silicon(:,1)==Esi(i,1));
            f2 = find(V_silicon(:,1)==Esi(i,2));
            f3 = find(V_silicon(:,1)==Esi(i,3));

            ncoeff = q*mun*Vt;

            %%% 1st element
            % n part
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1))...
                - ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))...
                - ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)));
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1))...
                + ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)));
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1))...
                + ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                - ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                - ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                - ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                - ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1);
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                + ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1);
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                + ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1);

            Res(X2(3*X1_sorted(Esi(i,1),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,1),2)-1,1),1)...
                + ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                - ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                + ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                - ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*n(f1);

            %%% 2nd element
            % n part
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1))...
                - ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,2),2)))...
                - ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,2),2)));
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1))...
                + ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,3),2)));
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1))...
                + ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,1),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                - ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                - ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                - ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                - ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2);
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                + ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2);
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                + ncoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2);

            Res(X2(3*X1_sorted(Esi(i,2),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,2),2)-1,1),1)...
                + ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                - ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                + ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                - ncoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*n(f2);

            %%% 3rd element
            % n part
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1))...
                - ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))...
                - ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)));
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1))...
                + ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)));
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1))...
                + ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                - ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                - ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                - ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                - ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3);
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                + ncoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3);
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                + ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)), phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                + ncoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)), phi(X1_sorted(Esi(i,3),2)))*n(f3);

            Res(X2(3*X1_sorted(Esi(i,3),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,3),2)-1,1),1)...
                + ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*n(f1)...
                - ncoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*n(f3)...
                + ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*n(f2)...
                - ncoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*n(f3);

            %%% n transient part
            Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2)-1,1), X2(3*X1_sorted(Esi(i,1),2)-1,1))...
                - q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,3)*edge(i,3))/deltaT;
            Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2)-1,1), X2(3*X1_sorted(Esi(i,2),2)-1,1))...
                - q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,2)*edge(i,2))/deltaT;
            Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2)-1,1), X2(3*X1_sorted(Esi(i,3),2)-1,1))...
                - q*0.25*(lenEsi(i,3)*edgeEsi(i,3)+lenEsi(i,2)*edge(i,2))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,1),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,1),2)-1,1),1)...
                - q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,3)*edge(i,3))*(n(f1) - old_n(f1))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,2),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,2),2)-1,1),1)...
                - q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,2)*edge(i,2))*(n(f2) - old_n(f2))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,3),2)-1,1),1) = Res(X2(3*X1_sorted(Esi(i,3),2)-1,1),1)...
                - q*0.25*(lenEsi(i,3)*edgeEsi(i,3)+lenEsi(i,2)*edge(i,2))*(n(f3) - old_n(f3))/deltaT;
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%% for hole DD
        for i=1:Esirow

            f1 = find(V_silicon(:,1)==Esi(i,1));
            f2 = find(V_silicon(:,1)==Esi(i,2));
            f3 = find(V_silicon(:,1)==Esi(i,3));

            pcoeff = q*mup/Vt;

            %%% 1st element
            % p part
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2),1))...
                + pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))...
                + pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)));
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,2),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,2),2),1))...
                - pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)));
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,3),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,3),2),1))...
                - pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                - pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2)...
                - pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1)...
                - pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3)...
                - pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1);
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2)...
                + pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1);
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3)...
                + pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1);

            Res(X2(3*X1_sorted(Esi(i,1),2),1),1) = Res(X2(3*X1_sorted(Esi(i,1),2),1),1)...
                - pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2)...
                + pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1)...
                - pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3)...
                + pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1);

            %%% 2nd element
            % p part
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2),1))...
                + pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))...
                + pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)));
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,3),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,3),2),1))...
                - pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)));
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,1),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,1),2),1))...
                - pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                - pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3)...
                - pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2)...
                - pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1)...
                - pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2);
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3)...
                + pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2);
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1)...
                + pcoeff/Vt*edgeEsi(i,1)/lenEsi(i,1)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2);

            Res(X2(3*X1_sorted(Esi(i,2),2),1),1) = Res(X2(3*X1_sorted(Esi(i,2),2),1),1)...
                - pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3)...
                + pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2)...
                - pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,2),2)))*p(f1)...
                + pcoeff*edgeEsi(i,1)/lenEsi(i,1)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,1),2)))*p(f2);

            %%% 3rd element
            % p part
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2),1))...
                + pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))...
                + pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)));
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,1),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,1),2),1))...
                - pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)));
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,2),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,2),2),1))...
                - pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)));

            % phi part
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2)-2,1))...
                - pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1)...
                - pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3)...
                - pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2)...
                - pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3);
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,1),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1)...
                + pcoeff/Vt*edgeEsi(i,3)/lenEsi(i,3)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3);
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,2),2)-2,1))...
                + pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2)...
                + pcoeff/Vt*edgeEsi(i,2)/lenEsi(i,2)*dbern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3);

            Res(X2(3*X1_sorted(Esi(i,3),2),1),1) = Res(X2(3*X1_sorted(Esi(i,3),2),1),1)...
                - pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,1),2)),phi(X1_sorted(Esi(i,3),2)))*p(f1)...
                + pcoeff*edgeEsi(i,3)/lenEsi(i,3)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,1),2)))*p(f3)...
                - pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,2),2)),phi(X1_sorted(Esi(i,3),2)))*p(f2)...
                + pcoeff*edgeEsi(i,2)/lenEsi(i,2)*bern(phi(X1_sorted(Esi(i,3),2)),phi(X1_sorted(Esi(i,2),2)))*p(f3);

            %%% p transient part
            Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,1),2),1), X2(3*X1_sorted(Esi(i,1),2),1))...
                + q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,3)*edge(i,3))/deltaT;
            Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,2),2),1), X2(3*X1_sorted(Esi(i,2),2),1))...
                + q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,2)*edge(i,2))/deltaT;
            Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2),1)) = Jaco(X2(3*X1_sorted(Esi(i,3),2),1), X2(3*X1_sorted(Esi(i,3),2),1))...
                + q*0.25*(lenEsi(i,3)*edgeEsi(i,3)+lenEsi(i,2)*edge(i,2))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,1),2),1),1) = Res(X2(3*X1_sorted(Esi(i,1),2),1),1)...
                + q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,3)*edge(i,3))*(p(f1) - old_p(f1))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,2),2),1),1) = Res(X2(3*X1_sorted(Esi(i,2),2),1),1)...
                + q*0.25*(lenEsi(i,1)*edgeEsi(i,1)+lenEsi(i,2)*edge(i,2))*(p(f2) - old_p(f2))/deltaT;
            Res(X2(3*X1_sorted(Esi(i,3),2),1),1) = Res(X2(3*X1_sorted(Esi(i,3),2),1),1)...
                + q*0.25*(lenEsi(i,3)*edgeEsi(i,3)+lenEsi(i,2)*edge(i,2))*(p(f3) - old_p(f3))/deltaT;
        end

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%% Dirichlet boundary condition for final iteration
        for i=1:(Ncon1+Ncon2)
            for j=1:concol
                fcon = X1_sorted(contact(i,j),2);
                fcon_np = find(contact(i,j)==V_silicon(:,1));

                Jaco(X2(3*fcon-2),:) = 0;
                Jaco(X2(3*fcon-1),:) = 0;
                Jaco(X2(3*fcon),:) = 0;

                Jaco(X2(3*fcon-2), X2(3*fcon-2)) = 1;
                Jaco(X2(3*fcon-1), X2(3*fcon-1)) = 1;
                Jaco(X2(3*fcon), X2(3*fcon)) = 1;

                % ground
                if i<=Ncon1
                    Res(X2(3*fcon-2),1) = phi(fcon) - Vt*log(Nd/nint);
                    Res(X2(3*fcon-1),1) = n(fcon_np) - Nd;
                    Res(X2(3*fcon),1) = p(fcon_np) - nint*nint/Nd;

                % input
                elseif i>(Ncon1) &&  i<=(Ncon1+Ncon2)
                    Res(X2(3*fcon-2),1) = phi(fcon) - Vt*log(Nd/nint) - Vex;
                    Res(X2(3*fcon-1),1) = n(fcon_np) - Nd;
                    Res(X2(3*fcon),1) = p(fcon_np) - nint*nint/Nd;
                end
            end
        end

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%% scaled part
        Cvector = zeros(size(Jaco,1),1);
        for i=1:size(Jaco,1)
            if rem(X2_sorted(i),3) == 1
                Cvector(i) = Vt;
            elseif rem(X2_sorted(i),3) == 2
                Cvector(i) = Nd;
            elseif rem(X2_sorted(i),3) == 0
                Cvector(i) = Nd;
            end
        end

        Cmatrix = spdiags(Cvector,0,size(X2_sorted,1),size(X2_sorted,1));
        Jaco_scaled = Jaco * Cmatrix;
        Rvector = 1./sum(abs(Jaco_scaled),2);
        Rmatrix = spdiags(Rvector,0,size(X2_sorted,1),size(X2_sorted,1));
        Jaco_scaled = Rmatrix * Jaco_scaled;
        Res_scaled = Rmatrix * Res;
        update_scaled = Jaco_scaled \ (-Res_scaled);
        update = Cmatrix * update_scaled;

        countphi=1;
        countn=1;
        countp=1;

        maxupdate = 0;
        for i=1:size(X2_sorted,1)
            if rem(X2_sorted(i),3) == 1
                phi(countphi) = phi(countphi) + update(i);
                if maxupdate < max(abs(update(i)))
                    maxupdate = max(abs(update(i)));
                end
                countphi = countphi+1;
            elseif rem(X2_sorted(i),3) == 2
                n(countn) = n(countn) + update(i);
                countn = countn + 1;
            elseif rem(X2_sorted(i),3) == 0
                p(countp) = p(countp) + update(i);
                countp = countp + 1;
            end
        end

        save_update(:,it) = update(:,1);
        save_phi_update(it,step) = maxupdate;

        if maxupdate < 1e-10
            break
        end
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%% current calculation

    for i = 1:size(uniconin,1)
        for j = 1:E4row
            fcon = find(uniconin(i) == E4(j,:));
            f1 = find(V_silicon(:,1) == E4(j,1));
            f2 = find(V_silicon(:,1) == E4(j,2));
            f3 = find(V_silicon(:,1) == E4(j,3));

            if fcon == 1
                In(step,1) = In(step,1) ...
                    + ncoeff*edgeE4(j,2)/lenE4(j,2)*(n(f2)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,2),2))) - n(f1)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,1),2))))*width...
                    + ncoeff*edgeE4(j,3)/lenE4(j,3)*(n(f3)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,3),2))) - n(f1)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,1),2))))*width;
                Ip(step,1) = Ip(step,1) ... 
                    - pcoeff*edgeE4(j,2)/lenE4(j,2)*(p(f2)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,1),2))) - p(f1)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,2),2))))*width...
                    - pcoeff*edgeE4(j,3)/lenE4(j,3)*(p(f3)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,1),2))) - p(f1)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,3),2))))*width;
                Id(step,1) = Id(step,1) ...               
                    - esi*e0*edgeE4(j,2)/lenE4(j,2)*(phi(X1_sorted(E4(j,2),2))-phi(X1_sorted(E4(j,1),2)) - old_phi(X1_sorted(E4(j,2),2))+old_phi(X1_sorted(E4(j,1),2)))/deltaT*width...
                    - esi*e0*edgeE4(j,3)/lenE4(j,3)*(phi(X1_sorted(E4(j,3),2))-phi(X1_sorted(E4(j,1),2)) - old_phi(X1_sorted(E4(j,3),2))+old_phi(X1_sorted(E4(j,1),2)))/deltaT*width;
            elseif fcon == 2
                In(step,1) = In(step,1) ...
                    + ncoeff*edgeE4(j,2)/lenE4(j,2)*(n(f3)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,3),2))) - n(f2)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,2),2))))*width...
                    + ncoeff*edgeE4(j,1)/lenE4(j,1)*(n(f1)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,1),2))) - n(f2)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,2),2))))*width;
                Ip(step,1) = Ip(step,1) ... 
                    - pcoeff*edgeE4(j,2)/lenE4(j,2)*(p(f3)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,2),2))) - p(f2)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,3),2))))*width...
                    - pcoeff*edgeE4(j,1)/lenE4(j,1)*(p(f1)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,2),2))) - p(f2)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,1),2))))*width;
                Id(step,1) = Id(step,1) ... 
                    - esi*e0*edgeE4(j,2)/lenE4(j,2)*(phi(X1_sorted(E4(j,3),2))-phi(X1_sorted(E4(j,2),2)) - old_phi(X1_sorted(E4(j,3),2))+old_phi(X1_sorted(E4(j,2),2)))/deltaT*width...
                    - esi*e0*edgeE4(j,1)/lenE4(j,1)*(phi(X1_sorted(E4(j,1),2))-phi(X1_sorted(E4(j,2),2)) - old_phi(X1_sorted(E4(j,1),2))+old_phi(X1_sorted(E4(j,2),2)))/deltaT*width;

            elseif fcon == 3
                In(step,1) = In(step,1) ...
                    + ncoeff*edgeE4(j,3)/lenE4(j,3)*(n(f3)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,1),2))) - n(f3)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,3),2))))*width...
                    + ncoeff*edgeE4(j,2)/lenE4(j,2)*(n(f2)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,2),2))) - n(f3)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,3),2))))*width;
                Ip(step,1) = Ip(step,1) ... 
                    - pcoeff*edgeE4(j,3)/lenE4(j,3)*(p(f3)*bern(phi(X1_sorted(E4(j,1),2)),phi(X1_sorted(E4(j,3),2))) - p(f3)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,1),2))))*width...
                    - pcoeff*edgeE4(j,2)/lenE4(j,2)*(p(f2)*bern(phi(X1_sorted(E4(j,2),2)),phi(X1_sorted(E4(j,3),2))) - p(f3)*bern(phi(X1_sorted(E4(j,3),2)),phi(X1_sorted(E4(j,2),2))))*width;
                Id(step,1) = Id(step,1) ... 
                    - esi*e0*edgeE4(j,3)/lenE4(j,3)*(phi(X1_sorted(E4(j,1),2))-phi(X1_sorted(E4(j,3),2)) - old_phi(X1_sorted(E4(j,1),2))+old_phi(X1_sorted(E4(j,3),2)))/deltaT*width...
                    - esi*e0*edgeE4(j,2)/lenE4(j,2)*(phi(X1_sorted(E4(j,2),2))-phi(X1_sorted(E4(j,3),2)) - old_phi(X1_sorted(E4(j,2),2))+old_phi(X1_sorted(E4(j,3),2)))/deltaT*width;
            end
        end
    end
end

I = In + Id;
