%%% drain current 
for i = 1:size(unicondr,1)
    for j = 1:Edrrow
        fcon = find(unicondr(i) == Edr(j,:));
        f1 = find(Vsi(:,1) == Edr(j,1));
        f2 = find(Vsi(:,1) == Edr(j,2));
        f3 = find(Vsi(:,1) == Edr(j,3));

        if fcon == 1
            In_drain(step,1) = In_drain(step,1) ...
                + ncoeff*Vt*edgeEdr(j,1)/lenEdr(j,1)*(n(f2)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,2),1))) - n(f1)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,1),1))))*width...
                + ncoeff*Vt*edgeEdr(j,3)/lenEdr(j,3)*(n(f3)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,3),1))) - n(f1)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,1),1))))*width;
            Ip_drain(step,1) = Ip_drain(step,1) ...
                - pcoeff*Vt*edgeEdr(j,1)/lenEdr(j,1)*(p(f2)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,1),1))) - p(f1)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,2),1))))*width...
                - pcoeff*Vt*edgeEdr(j,3)/lenEdr(j,3)*(p(f3)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,1),1))) - p(f1)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,3),1))))*width;

        elseif fcon == 2
            In_drain(step,1) = In_drain(step,1) ...
                + ncoeff*Vt*edgeEdr(j,2)/lenEdr(j,2)*(n(f3)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,3),1))) - n(f2)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,2),1))))*width...
                + ncoeff*Vt*edgeEdr(j,1)/lenEdr(j,1)*(n(f1)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,1),1))) - n(f2)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,2),1))))*width;
            Ip_drain(step,1) = Ip_drain(step,1) ...
                - pcoeff*Vt*edgeEdr(j,2)/lenEdr(j,2)*(p(f3)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,2),1))) - p(f2)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,3),1))))*width...
                - pcoeff*Vt*edgeEdr(j,1)/lenEdr(j,1)*(p(f1)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,2),1))) - p(f2)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,1),1))))*width;

        elseif fcon == 3
            In_drain(step,1) = In_drain(step,1) ...
                + ncoeff*Vt*edgeEdr(j,3)/lenEdr(j,3)*(n(f1)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,1),1))) - n(f3)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,3),1))))*width...
                + ncoeff*Vt*edgeEdr(j,2)/lenEdr(j,2)*(n(f2)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,2),1))) - n(f3)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,3),1))))*width;
            Ip_drain(step,1) = Ip_drain(step,1) ...
                - pcoeff*Vt*edgeEdr(j,3)/lenEdr(j,3)*(p(f1)*bern(phi(X1_sorted(Edr(j,1),1)),phi(X1_sorted(Edr(j,3),1))) - p(f3)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,1),1))))*width...
                - pcoeff*Vt*edgeEdr(j,2)/lenEdr(j,2)*(p(f2)*bern(phi(X1_sorted(Edr(j,2),1)),phi(X1_sorted(Edr(j,3),1))) - p(f3)*bern(phi(X1_sorted(Edr(j,3),1)),phi(X1_sorted(Edr(j,2),1))))*width;
        end
    end
end


%%% source current
for i = 1:size(uniconsr,1)
    for j = 1:Esrrow
        fcon = find(uniconsr(i) == Esr(j,:));
        f1 = find(Vsi(:,1) == Esr(j,1));
        f2 = find(Vsi(:,1) == Esr(j,2));
        f3 = find(Vsi(:,1) == Esr(j,3));

        if fcon == 1
            In_source(step,1) = In_source(step,1) ...
                + ncoeff*Vt*edgeEsr(j,1)/lenEsr(j,1)*(n(f2)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,2),1))) - n(f1)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,1),1))))*width...
                + ncoeff*Vt*edgeEsr(j,3)/lenEsr(j,3)*(n(f3)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,3),1))) - n(f1)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,1),1))))*width;
            Ip_source(step,1) = Ip_source(step,1) ...
                - pcoeff*Vt*edgeEsr(j,1)/lenEsr(j,1)*(p(f2)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,1),1))) - p(f1)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,2),1))))*width...
                - pcoeff*Vt*edgeEsr(j,3)/lenEsr(j,3)*(p(f3)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,1),1))) - p(f1)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,3),1))))*width;

        elseif fcon == 2
            In_source(step,1) = In_source(step,1) ...
                + ncoeff*Vt*edgeEsr(j,2)/lenEsr(j,2)*(n(f3)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,3),1))) - n(f2)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,2),1))))*width...
                + ncoeff*Vt*edgeEsr(j,1)/lenEsr(j,1)*(n(f1)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,1),1))) - n(f2)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,2),1))))*width;
            Ip_source(step,1) = Ip_source(step,1) ...
                - pcoeff*Vt*edgeEsr(j,2)/lenEsr(j,2)*(p(f3)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,2),1))) - p(f2)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,3),1))))*width...
                - pcoeff*Vt*edgeEsr(j,1)/lenEsr(j,1)*(p(f1)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,2),1))) - p(f2)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,1),1))))*width;

        elseif fcon == 3
            In_source(step,1) = In_source(step,1) ...
                + ncoeff*Vt*edgeEsr(j,3)/lenEsr(j,3)*(n(f1)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,1),1))) - n(f3)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,3),1))))*width...
                + ncoeff*Vt*edgeEsr(j,2)/lenEsr(j,2)*(n(f2)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,2),1))) - n(f3)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,3),1))))*width;
            Ip_source(step,1) = Ip_source(step,1) ...
                - pcoeff*Vt*edgeEsr(j,3)/lenEsr(j,3)*(p(f1)*bern(phi(X1_sorted(Esr(j,1),1)),phi(X1_sorted(Esr(j,3),1))) - p(f3)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,1),1))))*width...
                - pcoeff*Vt*edgeEsr(j,2)/lenEsr(j,2)*(p(f2)*bern(phi(X1_sorted(Esr(j,2),1)),phi(X1_sorted(Esr(j,3),1))) - p(f3)*bern(phi(X1_sorted(Esr(j,3),1)),phi(X1_sorted(Esr(j,2),1))))*width;
        end
    end
end
